version: '3.5'

services:
  back:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/:/usr/src/app
    ports:
      - 3003:3003
    container_name: bloglist-back
  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/:/usr/src/app
    ports:
      - 3000:3000
    container_name: bloglist-front
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8080:80"
    container_name: reserve-proxy